// данные для событий

const SCHEDULE__DATA = [
    {
        taskId: "10001",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "01.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10002",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "12.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10003",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "15.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10004",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Продавец",
        date: "20.09.2022",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        taskId: "10005",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "20.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },

    {
        taskId: "10006",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "01.10.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10007",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "12.10.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10008",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "15.10.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10009",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "20.10.2022",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        taskId: "10010",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "20.10.2022",
        startTime: "9:00",
        endTime: "10:00",
    },

    {
        taskId: "10011",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "05.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10012",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "11.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10013",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "18.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },
    {
        taskId: "10014",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "21.09.2022",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        taskId: "10015",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "23.09.2022",
        startTime: "9:00",
        endTime: "10:00",
    },

    {
        taskId: "10016",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "26.09.2022",
        startTime: "8:00",
        endTime: "10:00",
    },
    {
        taskId: "10017",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "26.09.2022",
        startTime: "12:00",
        endTime: "13:00",
    },

    {
        taskId: "10018",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Продавец",
        date: "26.09.2022",
        startTime: "12:30",
        endTime: "13:30",
    },
    {
        taskId: "10019",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "27.09.2022",
        startTime: "9:30",
        endTime: "10:30",
    },
    {
        taskId: "10020",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "27.09.2022",
        startTime: "11:30",
        endTime: "12:30",
    },
    {
        taskId: "10021",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Кассир",
        date: "28.09.2022",
        startTime: "11:00",
        endTime: "11:45",
    },
    {
        taskId: "10022",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "27.09.2022",
        startTime: "8:15",
        endTime: "9:15",
    },

    // 04.10.2022

    {
        taskId: "10023",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "04.10.2022",
        startTime: "11:30",
        endTime: "12:30",
    },
    {
        taskId: "10024",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "8:15",
        endTime: "9:15",
    },
    {
        taskId: "10025",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "10:45",
        endTime: "11:15",
    },
    {
        taskId: "10026",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "8:45",
        endTime: "9:15",
    },
    {
        taskId: "10027",
        type: "offer",
        typeTitle: "Оффер",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "10:15",
        endTime: "11:15",
    },
    {
        taskId: "10028",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "12:15",
        endTime: "13:15",
    },

    {
        taskId: "10029",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },

    {
        taskId: "10030",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "04.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },

    {
        taskId: "10034",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "11:00",
        endTime: "11:30",
    },

    {
        taskId: "10035",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Продавец",
        date: "04.10.2022",
        startTime: "11:15",
        endTime: "11:45",
    },

    // 05.10.2022

    {
        taskId: "10036",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "05.10.2022",
        startTime: "9:15",
        endTime: "10:15",
    },
    {
        taskId: "10037",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "8:15",
        endTime: "9:15",
    },

    {
        taskId: "10038",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "8:45",
        endTime: "9:15",
    },
    {
        taskId: "10039",
        type: "offer",
        typeTitle: "Оффер",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "14:15",
        endTime: "15:00",
    },
    {
        taskId: "10040",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "17:15",
        endTime: "18:15",
    },

    {
        taskId: "10041",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "18:30",
        endTime: "19:30",
    },

    {
        taskId: "10042",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "05.10.2022",
        startTime: "19:30",
        endTime: "20:30",
    },

    {
        taskId: "10043",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "05.10.2022",
        startTime: "17:00",
        endTime: "17:30",
    },

    {
        taskId: "10044",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "06.10.2022",
        startTime: "09:15",
        endTime: "15:00",
    },

    // 10-13.10.2022

    {
        taskId: "10045",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "10.10.2022",
        startTime: "11:30",
        endTime: "12:30",
    },
    {
        taskId: "10046",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "10.10.2022",
        startTime: "8:15",
        endTime: "9:15",
    },
    {
        taskId: "10047",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "12.10.2022",
        startTime: "10:45",
        endTime: "11:15",
    },
    {
        taskId: "10048",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Продавец",
        date: "12.10.2022",
        startTime: "8:45",
        endTime: "9:15",
    },
    {
        taskId: "10049",
        type: "offer",
        typeTitle: "Оффер",
        title: "Продавец",
        date: "13.10.2022",
        startTime: "10:15",
        endTime: "11:15",
    },
    {
        taskId: "10050",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "14.10.2022",
        startTime: "12:15",
        endTime: "13:15",
    },

    {
        taskId: "10051",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "14.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },

    {
        taskId: "10052",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "15.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },

    {
        taskId: "10053",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "13.10.2022",
        startTime: "11:00",
        endTime: "11:30",
    },

    {
        taskId: "10054",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Продавец",
        date: "13.10.2022",
        startTime: "11:15",
        endTime: "11:45",
    },

    // 16-16.10.2022

    {
        taskId: "10055",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "16.10.2022",
        startTime: "11:30",
        endTime: "12:30",
    },
    {
        taskId: "10056",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "8:15",
        endTime: "9:15",
    },
    {
        taskId: "10057",
        type: "phonecall",
        typeTitle: "Аудиозвонок",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "10:45",
        endTime: "11:15",
    },
    {
        taskId: "10058",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "8:45",
        endTime: "9:15",
    },
    {
        taskId: "10059",
        type: "offer",
        typeTitle: "Оффер",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "10:15",
        endTime: "11:15",
    },
    {
        taskId: "10060",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "12:15",
        endTime: "13:15",
    },

    {
        taskId: "10061",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },

    {
        taskId: "10062",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "16.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },



    {
        taskId: "10063",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "11:00",
        endTime: "11:30",
    },

    {
        taskId: "10064",
        type: "videocall",
        typeTitle: "Видеособеседование",
        title: "Продавец",
        date: "16.10.2022",
        startTime: "11:15",
        endTime: "11:45",
    },

    {
        taskId: "10065",
        type: "office",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "16.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },
    {
        taskId: "10066",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "16.10.2022",
        startTime: "9:30",
        endTime: "12:30",
    },
    {
        taskId: "10067",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "16.10.2022",
        startTime: "9:30",
        endTime: "10:45",
    },

    {
        taskId: "10068",
        type: "test",
        typeTitle: "Тест/анкета",
        title: "Кассир",
        date: "17.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },
    {
        taskId: "10069",
        type: "office",
        typeTitle: "Интервью в офисе",
        title: "Кассир",
        date: "17.10.2022",
        startTime: "10:45",
        endTime: "11:30",
    },
    {
        taskId: "10070",
        type: "work",
        typeTitle: "Выход на работу",
        title: "Кассир",
        date: "17.10.2022",
        startTime: "9:30",
        endTime: "10:30",
    },


];

const workCalendarURL = 'https://raw.githubusercontent.com/d10xa/holidays-calendar/e10e1e195db86a0db138dcb0f6bb7f56ac44bb1d/json/calendar.json';

var workCalendarJSON = {} //тут у нас будет результат
var xhr = new XMLHttpRequest();
xhr.open('GET', workCalendarURL, false);
xhr.send();
if (xhr.status != 200) {
    // обработать ошибку
    alert(xhr.status + ': ' + xhr.statusText); // пример вывода: 404: Not Found
} else {
    // вывести результат
    workCalendarJSON = xhr.responseText;
}

// console.log(workCalendarData);




export { SCHEDULE__DATA, workCalendarJSON }
